"""DocumentsD

Revision ID: 3648596d5ead
Revises: 168d0b933e50
Create Date: 2024-08-10 06:47:04.411673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3648596d5ead'
down_revision: Union[str, None] = '168d0b933e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
