"""Tasks

Revision ID: b302a4ec9347
Revises: 706fe83fc07e
Create Date: 2024-08-10 02:49:40.064362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b302a4ec9347'
down_revision: Union[str, None] = '706fe83fc07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tasks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('checkbox_tasks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('necessary_resources', sa.String(), nullable=True),
    sa.Column('desired_result', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tasks')
    # ### end Alembic commands ###
