"""Deadline_date swap

Revision ID: 25912b0d4282
Revises: 7e6556a685a8
Create Date: 2024-08-09 22:14:29.161351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25912b0d4282'
down_revision: Union[str, None] = '7e6556a685a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deadline_date', sa.DateTime(), nullable=False))
    op.drop_column('columns', 'deadline_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('deadline_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('cards', 'deadline_date')
    # ### end Alembic commands ###
