"""UserIDandServices

Revision ID: 9a0afdf38175
Revises: b9bbed94bd26
Create Date: 2024-08-11 02:37:02.420560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0afdf38175'
down_revision: Union[str, None] = 'b9bbed94bd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('total_work_price', sa.Integer(), nullable=True),
    sa.Column('total_operation_price', sa.Integer(), nullable=True),
    sa.Column('total_material_price', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimates',
    sa.Column('position_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_work_price', sa.Integer(), nullable=False),
    sa.Column('unit_operation_price', sa.Integer(), nullable=False),
    sa.Column('unit_material_price', sa.Integer(), nullable=False),
    sa.Column('work_price', sa.Integer(), nullable=True),
    sa.Column('operation_price', sa.Integer(), nullable=True),
    sa.Column('material_price', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('creator_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'creator_id')
    op.drop_table('estimates')
    op.drop_table('chapters')
    # ### end Alembic commands ###
